export const counties = [
  { value: '', label: '請選擇居住縣市' },
  { value: '1', label: '臺北市' },
  { value: '2', label: '基隆市' },
  { value: '3', label: '新北市' },
  { value: '4', label: '宜蘭縣' },
  { value: '5', label: '新竹市' },
  { value: '6', label: '新竹縣' },
  { value: '7', label: '桃園市' },
  { value: '8', label: '苗栗縣' },
  { value: '9', label: '臺中市' },
  { value: '10', label: '彰化縣' },
  { value: '11', label: '南投縣' },
  { value: '12', label: '嘉義市' },
  { value: '13', label: '嘉義縣' },
  { value: '14', label: '雲林縣' },
  { value: '15', label: '臺南市' },
  { value: '16', label: '高雄市' },
  { value: '17', label: '南海諸島' },
  { value: '18', label: '澎湖縣' },
  { value: '19', label: '屏東縣' },
  { value: '20', label: '臺東縣' },
  { value: '21', label: '花蓮縣' },
  { value: '22', label: '金門縣' },
  { value: '23', label: '連江縣' },
]
